version: "3.8"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=test_db
      - PUID=1000
      - PGID=1000
    expose:
      - 27017
    networks:
      compose_net:
        ipv4_address: 172.20.0.2
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./mongodb/init.js:/docker-entrypoint.initdb.d/init.js

  sparkapi:
    build: ./api
    depends_on:
      - mongodb
    expose:
      - 8080
    networks:
      compose_net:
        ipv4_address: 172.20.0.3
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  compose_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
